# Generated by Django 4.2.16 on 2024-09-20 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_alter_order_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='slug',
            field=models.SlugField(blank=True, editable=False, max_length=255, null=True, verbose_name='Slug'),
        ),
    ]
